export enum ScreenNames {
  LOGIN_PAGE = 'LOGIN_PAGE',
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  LOGGED_IN_STACK = 'LOGGED_IN_STACK',
  LOGGED_OUT_STACK = 'LOGGED_OUT_STACK',
  TAB_BAR_STACK = 'TAB_BAR_STACK',
  DICTIONARY_PAGE = 'DICTIONARY_PAGE',
  RECOMMEND_PAGE = 'RECOMMEND_PAGE',
  TRAINING_PAGE = 'TRAINING_PAGE',
  ADD_WORD_PAGE = 'ADD_WORD_PAGE',
}
